apiVersion: v1
kind: Service
metadata:
  labels:
    app: teamspeak
  name: teamspeak
spec:
  ports:
  - name: 30010to9987
    nodePort: 30010
    port: 9987
    protocol: UDP
    targetPort: 9987
  - name: 30011to10011
    nodePort: 30011
    port: 10011
    protocol: TCP
    targetPort: 10011
  - name: 30012to30033
    nodePort: 30012
    port: 30033
    protocol: TCP
    targetPort: 30033
  selector:
    app: teamspeak
  type: NodePort